### PR TITLE
new project structure with project.json

### PR DESCRIPTION
**Pull request by StefH**
- new project structure with project.json
- supports .NETPortable,Version=v4.6,Profile=Profile151 and .NETPortable,Version=v4.5,Profile=Profile111
- create a single NuGet with _build nuget.cmd

### CODE REVIEW

**Comment by DecaTec** [comment]
Hey, thanks for you support.
I'll have a closer look at the changes and do some testing if everything still works as expected.

**Comment by StefH** [comment]
I can also upload the package to NuGet.org and add you as second author/admin to NuGet.

**Comment by DecaTec** [comment]
Let me first take a look at the changes. I'll create a Nuget package as soon as the new project structure gets into a new version (maybe along with issue #8 ).

**Comment by DecaTec** [comment]
I took a quick look at the changes now. Unfortunately, I figured out a few problems:
-  I wasn't able to open the solution with a "blank" VS 2015 Update 3 because of the xproj file. I had to install the "MS .NET Core 1.0.0 VS 2015 Tooling Preview 2". This is still a preview  and not a final version.
- On both target frameworks, the HTTP requests are accomplished by System.Net.Http.HttpClient. At the moment, I'll have to use Windows.Web.Http.HttpClient for the HTTP requests on UWP apps. Yes, you could also use  System.Net.Http.HttpClient here, but this leads to some problems (see the other/closed issues). 

So I really appreciate your support here, but at the moment I'll stick to the current project structure. As already mentioned, the split into a .NET and a UWP part of the lib was just done because of problems with System.Net.Http.HttpClient with UWP apps and will probably get obsolete one day.
I'll keep the pull request in mind, in the future this is probably the way to go.

**Pull request closed without merging**
