### PR TITLE
Add missing CancellationToken overloads

### PR DESCRIPTION
**Pull request by TomGroeneboer**
Add LOCK/UNLOCK overloads that only accept CancellationToken without HttpCompletionOption.

### CODE REVIEW

**Comment by DecaTec** [comment]
Thanks for the PR!
I have very little time at the moment, so I think I will merge and prepare for new version on Friday.

Speaking of, I'll also have a look at other overloads that are still missing. Do you miss any more overloads?

**Comment by TomGroeneboer** [comment]
That's alright, for now we'll create a NuGet package on our own MyGet feed and switch to your version when released. 

We'll have a look at the overloads and add some if we see missing ones.

**Comment by DecaTec** [comment]
Great! Thanks a lot!

**Comment by DecaTec** [comment]
v1.1.3.0 released. 
I've only found a missing overload in `WebDavSession`.

**Comment by TomGroeneboer** [comment]
Great, thanks! :)

**Pull request merged**
